apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: be-rollout
  namespace: argo-rollouts
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: {}
        - setWeight: 100
  selector:
    matchLabels:
      app: be-app
  template:
    metadata:
      labels:
        app: be-app
    spec:
      containers:
      - name: be-container
        image: node:20
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: mydb

---
apiVersion: v1 
kind: Service
metadata:
  name: be-service
  namespace: argo-rollouts
spec:
  selector:
    app: be-app
  ports:
  - port: 3000
    targetPort: 3000