apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: argo-rollouts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        volumeMounts:
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-scripts
        configMap:
          name: postgres-init-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: argo-rollouts
spec:
  ports:
  - port: 5432
  selector:
    app: postgres


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: argo-rollouts
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS activities (
      id SERIAL PRIMARY KEY,
      activity VARCHAR(255)
    );
    INSERT INTO activities (activity) VALUES ('Hello');
