apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fe-rollout
  namespace: argo-rollouts
spec:
  replicas: 3
  strategy: 
    canary:
      steps:
        - setWeight: 50
        - pause: {}
        - setWeight: 100
  selector:
    matchLabels:
      app: fe-app
  template:
    metadata:
      labels:
        app: fe-app
    spec:
      containers:
      - name: fe-container
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fe-service
  namespace: argo-rollouts
spec:
  selector: 
    app: fe-app
  ports:
  - port: 80
    targetPort: 80